name: CI

on:
  push:
    branches:
      - main
      - sweeper
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - run: ./gradlew assembleDebug --warning-mode all --stacktrace
      - run: ./gradlew lintDebug --warning-mode all --stacktrace

